### ISSUE TITLE
Kann keinen char erstellen

### ISSUE THREAD

**Issue by Dustinn3** [MissShuwa/SakuraLife#1]
Kann keinen char erstellen

**Comment by Dustinn3** [comment]
bekomme diese fehlermeldung: [  script:sakura_core] Error loading script server.lua in resource sakura_core: @sakura_core/server.lua:7: attempt to index a nil value (local 'ESX')
[  script:sakura_core] stack traceback:
[  script:sakura_core] 	@sakura_core/server.lua:7: in main chunk und habe auch nichts dran verändert

**Comment by MissShuwa** [comment]
Das ist mehr ein Fehler in der Core schreib mir mal auf Discord werde dir da gerne weiterhelfen.

Aysa#0001

**Comment by MissShuwa** [comment]
Update Version will be coming Today
